### PR TITLE
fix decode hello message error when caps name too long

### PR DESCRIPTION
**Pull request by clouds56**

### CODE REVIEW

**Comment by vorot93** [comment]
This will cause unnecessary allocation, what is the capability in question?

**Comment by clouds56** [comment]
Or we could use things like enum to mitigate
```rust
enum CapabilityName {
  Small(ArrayString),
  Large(String),
}
```
As you could see in example, much client have `istanbul` as capability which could not fix in `[u8; 4]` and causes 

> disconnected with error: hello failed (rlp)

**Comment by gelfand** [comment]
> As you could see in example, much client have `istanbul` as capability which could not fix in `[u8; 4]` and causes

I've never seen `istanbul` as capability, can you point whatever client that is?

**Comment by clouds56** [comment]
Seems in some modified Geth, I cannot find anywhere in spec restricts the capability name to `<=4`

> Geth/*****/v1.10.0-stable(quorum-v22.1.0)/linux-amd64/go1.17.2

**Pull request closed without merging**
